server:
  port: 8986



app:
  path:
    project: /opt/projects/todo
    files: /files/

logging:
  level:
    root: DEBUG


db:
  todo:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      hbm2ddl:
        auto: validate
